#!/bin/bash -login

#PBS -l walltime=8:00:00,nodes=1:ppn=8,mem=24gb
#PBS -N occ_cegma_paper
#PBS -A ged-intel11
#PBS -M elijahlowe@gmail.com
#PBS -m abe

module load CEGMA

GENOME='/mnt/home/loweelij/genomes/Mocc_genome_v1.1.fa'
mkdir /mnt/scratch/loweelij/cegma/paper_mocc/
cd /mnt/scratch/loweelij/cegma/paper_mocc/
cegma -g $GENOME -T 8 -o /mnt/scratch/loweelij/cegma/paper_mocc/cegma_paper_mocc

qstat -f ${PBS_JOBID}

