#!/bin/bash -login

#PBS -l walltime=8:00:00,nodes=1:ppn=8,mem=24gb
#PBS -N moxi_cegma_paper
#PBS -A ged-intel11
#PBS -M elijahlowe@gmail.com
#PBS -m abe

module load CEGMA

GENOME='/mnt/home/loweelij/genomes/Moxi_genome_v1.2.fa'
mkdir /mnt/scratch/loweelij/cegma/paper_moxi/
cd /mnt/scratch/loweelij/cegma/paper_moxi/
cegma -g $GENOME -T 8 -o /mnt/scratch/loweelij/cegma/paper_moxi/cegma_paper_moxi

qstat -f ${PBS_JOBID}

