#!/bin/bash -login

#PBS -l walltime=96:00:00,nodes=1:ppn=4,mem=200gb
#PBS -N occulta_genome_c10
#PBS -A ged-intel11
#PBS -M elijahlowe@gmail.com
#PBS -m abe

module load velvet
module load khmer
module load screed

WRKSP='/mnt/scratch/loweelij/genome_assembly/mocc/c10/'
mkdir ${WRKSP}
cd ${WRKSP}
ln -fs /mnt/home/loweelij/occulta/*trim.gz .
for i in *R1*trim.gz; do interleave-reads.py $i ${i/R1/R2} > ${i/R1/interleave};done
for i in *interleave*; do mv $i ${i/.gz.trim.gz/};done
for i in *interleave*fastq; do normalize-by-median.py -p -k 20 -C 10 -N 4 -x 4e9 -s $i.kh $i;done
for i in *interleave*keep; do filter-abund.py -V ${i/keep/.kh} $i;done
for i in *abundfilt; do extract-paired-reads.py $i;done
cat *abundfilt.se > single.fq
velveth ${WRKSP}output 21,72,10 -fastq -shortPaired A_MOcculta_342_CGATGT_L006_interleave_001.fastq.keep.abundfilt.pe -shortPaired2 A_MOcculta_683_GCCAAT_L007_interleave_001.fastq.keep.abundfilt.pe -shortPaired3 A_MOcculta_807_GCCAAT_L008_interleave_001.fastq.keep.abundfilt.pe -short single.fq
for((i=21;i<=71;i=i+10));do velvetg ${WRKSP}output_"$i" -cov_cutoff auto -exp_cov auto -ins_length 340 -ins_length2 680 -ins_length3 810 -min_contig_lgth 200;done

qstat -f ${PBS_JOBID}